# Alacritty Configuration
# Save as: ~/.config/alacritty/alacritty.toml

[env]
TERM = "xterm-256color"

[window]
# Window padding (similar to Ghostty)
padding = { x = 2, y = 2 }

# Window decorations: Full | None | Transparent | Buttonless
decorations = "Full"

# Startup mode: Windowed | Maximized | Fullscreen
startup_mode = "Windowed"

# Window opacity (0.0 - 1.0)
opacity = 1.0

# Window title
title = "Alacritty"

# Allow terminal applications to change title
dynamic_title = true

[scrolling]
# Maximum number of lines in scrollback buffer
history = 10000

# Number of lines scrolled per scroll action
multiplier = 3

[font]
# Font family - matches your Ghostty config
normal = { family = "Iosevka Term Nerd Font", style = "Regular" }
bold = { family = "Iosevka Term Nerd Font", style = "Bold" }
italic = { family = "Iosevka Term Nerd Font", style = "Italic" }
bold_italic = { family = "Iosevka Term Nerd Font", style = "Bold Italic" }
builtin_box_drawing = true

# Font size - matches your Ghostty config
size = 12.0

# Offset adjustments (similar to Ghostty's adjust settings)
offset = { x = 0, y = 3 }

# Glyph offset for better alignment
glyph_offset = { x = 0, y = 0 }

[selection]
# Colors for selected text
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# Save terminal selection to clipboard when released
save_to_clipboard = true

[cursor]
# Cursor style: Block | Underline | Beam
style = { shape = "Block", blinking = "Off" }

# Vi mode cursor style
vi_mode_style = { shape = "Block", blinking = "Off" }

# Thickness of cursor relative to cell width (0.0 - 1.0)
thickness = 0.15

[terminal]
# OSC 52 clipboard support
osc52 = "OnlyCopy"

[mouse]
# Hide cursor when typing
hide_when_typing = true

[hints]
# URL launcher
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
# Key bindings
bindings = [
  # Quick reload config
  { key = "Comma", mods = "Control|Shift", action = "CreateNewWindow" },

  # Copy/Paste
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },

  # Search
  { key = "F", mods = "Control|Shift", action = "SearchForward" },
  { key = "B", mods = "Control|Shift", action = "SearchBackward" },

  # Font size
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },

  # Scrolling
  { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
  { key = "Home", mods = "Shift", action = "ScrollToTop" },
  { key = "End", mods = "Shift", action = "ScrollToBottom" },

  # Vi mode
  { key = "Space", mods = "Shift|Control", mode = "~Search", action = "ToggleViMode" },

  # New instance
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]

[debug]
# Debug options
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false

# Nightfox Alacritty Colors
## name: carbonfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/carbonfox/alacritty.toml

[colors.primary]
background = "#161616"
foreground = "#f2f4f8"
dim_foreground = "#b6b8bb"
bright_foreground = "#f9fbff"

[colors.cursor]
text = "#f2f4f8"
cursor = "#b6b8bb"

[colors.vi_mode_cursor]
text = "#f2f4f8"
cursor = "#33b1ff"

[colors.search.matches]
foreground = "#f2f4f8"
background = "#525253"

[colors.search.focused_match]
foreground = "#f2f4f8"
background = "#3ddbd9"

[colors.footer_bar]
foreground = "#f2f4f8"
background = "#353535"

[colors.hints.start]
foreground = "#f2f4f8"
background = "#3ddbd9"

[colors.hints.end]
foreground = "#f2f4f8"
background = "#353535"

[colors.selection]
text = "#f2f4f8"
background = "#2a2a2a"

[colors.normal]
black = "#282828"
red = "#ee5396"
green = "#25be6a"
yellow = "#08bdba"
blue = "#78a9ff"
magenta = "#be95ff"
cyan = "#33b1ff"
white = "#dfdfe0"

[colors.bright]
black = "#484848"
red = "#f16da6"
green = "#46c880"
yellow = "#2dc7c4"
blue = "#8cb6ff"
magenta = "#c8a5ff"
cyan = "#52bdff"
white = "#e4e4e5"

[colors.dim]
black = "#222222"
red = "#ca4780"
green = "#1fa25a"
yellow = "#07a19e"
blue = "#6690d9"
magenta = "#a27fd9"
cyan = "#2b96d9"
white = "#bebebe"
